### ISSUE TITLE
[Bug] World of Warcraft "specific argument was out of range of valid values"

### ISSUE THREAD

**Issue by Dajova** [LemmusLemmus/GlosSI-Integration-Playnite#34]
![image](https://i.imgur.com/R5I5JzG.png)

Image says it all.

I can add other Blizzard games to the integration, but not WoW, it seems.

**Comment by LemmusLemmus** [comment]
Thanks for reporting the bug!
I can see where the error is thrown, but the question is why.
It would be very helpful if you provided the contents of the `extensions.log` file (located at `%AppData%\Playnite`), or at least the parts that relate to the error.

**Comment by Dajova** [comment]
From what i can see, this is what the file throws out that is related:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: The file extension of the image () is not supported by Steam.
   at GlosSIIntegration.Models.SteamGameAssets.Asset.SetCurrentImage(String filePath) in C:\Build\Easter\Egg\Source\Models\SteamGameAssets.cs:line 124
   at GlosSIIntegration.Models.PlayniteGameSteamAssets.SetHero(String filePath, Boolean overwrite) in C:\Build\Easter\Egg\Source\Models\PlayniteGameSteamAssets.cs:line 108
   at GlosSIIntegration.Models.PlayniteGameSteamAssets.TrySetAsset(String filePath, Boolean overwrite, Action`2 setImageAction) in C:\Build\Easter\Egg\Source\Models\PlayniteGameSteamAssets.cs:line 68
   at GlosSIIntegration.Models.PlayniteGameSteamAssets.SetFromPlayniteAssets(Boolean overwrite) in C:\Build\Easter\Egg\Source\Models\PlayniteGameSteamAssets.cs:line 53
   at GlosSIIntegration.Models.GlosSITargets.Files.GameGlosSITargetFile.Create(String iconPath) in C:\Build\Easter\Egg\Source\Models\GlosSITargets\Files\GameGlosSITargetFile.cs:line 38
   at GlosSIIntegration.Models.GlosSITargets.Files.GameGlosSITargetFile.Create() in C:\Build\Easter\Egg\Source\Models\GlosSITargets\Files\GameGlosSITargetFile.cs:line 58
   at GlosSIIntegration.GlosSIIntegration.<>c.<AddGamesProcess>b__72_0(Game game) in C:\Build\Easter\Egg\Source\GlosSIIntegration.cs:line 394
   at GlosSIIntegration.GlosSIIntegration.ProcessGames(List`1 games, GlobalProgressActionArgs progressBar, String errorMessage, Predicate`1 process) in C:\Build\Easter\Egg\Source\GlosSIIntegration.cs:line 357
   ```

**Comment by LemmusLemmus** [comment]
Tack för att du bifogade felmeddelandet!

The error happens when the extension tries to copy/reference the images from Playnite to the Steam shortcut. One of the files apparently have an unsupported file extension, and I had simply forgot an early exit when it is found to be invalid...

I have released a new version of the extension that should fix the issue. If it still does not work, please let me know!

**Comment by Dajova** [comment]
Well, i dont know if it works in general, because everytime i try to launch a game with the integration, the entire computer crawls to a standstill. I had to forcefully reboot the PC twice now, because of that. I'm not sure if its because of this update or not or even if its because of the extension at al, because GlosSl itself will just use 100% of my cpu whenever i try to run anything at al. In short, it's unusable for me.

**Comment by LemmusLemmus** [comment]
Ehrm, the update should definitely not do that. I guess you could try creating and starting a glossi shortcut without using Playnite to check whether the extension is involved at all, but I frankly see no reason as to why the extension would cause such behaviour.

Sorry for not being able to help further.
